"""
Interactive discovery API for knowledge exploration.
"""

from typing import List
from src.discovery.engine import KnowledgeDiscoveryEngine
from src.discovery.models.result import DiscoveryResult
from src.discovery.models.pattern import Pattern
from src.discovery.models.gap import KnowledgeGap
from src.discovery.models.insight import Insight
from src.core.relation_model import Relation


class InteractiveDiscovery:
    """
    Interactive knowledge exploration API.

    Provides methods for exploring knowledge:
    - Find relations for a concept
    - Search patterns by keyword
    - Analyze gaps in a domain
    - Ask natural language questions
    """

    def __init__(self, engine: KnowledgeDiscoveryEngine):
        """
        Initialize interactive discovery.

        Args:
            engine: Knowledge discovery engine instance
        """
        self.engine = engine
        self._last_result: DiscoveryResult = None

    def discover_and_store(self,
                          documents: List,
                          concepts: List,
                          relations: List = None) -> DiscoveryResult:
        """
        Run discovery and store results for interactive exploration.

        Args:
            documents: List of documents
            concepts: List of concepts
            relations: Optional existing relations

        Returns:
            DiscoveryResult
        """
        self._last_result = self.engine.discover(documents, concepts, relations)
        return self._last_result

    def explore_relations(self, concept_name: str) -> List[Relation]:
        """
        Explore relations for a specific concept.

        Args:
            concept_name: Name of concept to explore

        Returns:
            List of relations involving the concept
        """
        if not self._last_result:
            return []

        return [
            rel for rel in self._last_result.relations
            if rel.source_concept == concept_name or rel.target_concept == concept_name
        ]

    def find_patterns(self, keyword: str) -> List[Pattern]:
        """
        Find patterns containing a keyword.

        Args:
            keyword: Keyword to search for

        Returns:
            List of matching patterns
        """
        if not self._last_result:
            return []

        keyword_lower = keyword.lower()

        return [
            pattern for pattern in self._last_result.patterns
            if keyword_lower in pattern.title.lower() or
               keyword_lower in pattern.description.lower() or
               any(keyword_lower in c.lower() for c in pattern.related_concepts)
        ]

    def analyze_gaps_in_domain(self, domain: str) -> List[KnowledgeGap]:
        """
        Analyze gaps for a specific domain.

        Args:
            domain: Domain keyword

        Returns:
            List of relevant gaps
        """
        if not self._last_result:
            return []

        domain_lower = domain.lower()

        return [
            gap for gap in self._last_result.gaps
            if domain_lower in gap.description.lower() or
               any(domain_lower in c.lower() for c in gap.affected_concepts)
        ]

    def get_top_insights(self, n: int = 10) -> List[Insight]:
        """
        Get top N insights by significance.

        Args:
            n: Number of insights to return

        Returns:
            Top N insights
        """
        if not self._last_result:
            return []

        return self._last_result.insights[:n]

    def ask_question(self, question: str) -> str:
        """
        Ask a natural language question about the knowledge base.

        Args:
            question: Natural language question

        Returns:
            Answer generated by LLM
        """
        # Generate context from last result
        context = self._generate_context_summary()

        prompt = f"""基于以下知识发现结果，回答问题：

知识库摘要：
{context}

问题：{question}

请提供简洁、准确的答案。
"""

        response = self.engine.llm.generate(
            prompt=prompt,
            max_tokens=500,
            temperature=0.5
        )

        return response

    def _generate_context_summary(self) -> str:
        """Generate summary of discovery results for LLM context."""
        if not self._last_result:
            return "No discovery results available."

        summary_parts = []

        # Relations summary
        summary_parts.append(
            f"发现了 {len(self._last_result.relations)} 个关系"
        )

        # Patterns summary
        if self._last_result.patterns:
            top_patterns = self._last_result.patterns[:3]
            pattern_titles = [p.title for p in top_patterns]
            summary_parts.append(
                f"主要模式：{', '.join(pattern_titles)}"
            )

        # Gaps summary
        high_priority_gaps = [
            g for g in self._last_result.gaps
            if g.priority >= 7
        ]
        if high_priority_gaps:
            summary_parts.append(
                f"发现 {len(high_priority_gaps)} 个高优先级知识缺口"
            )

        # Top insights
        if self._last_result.insights:
            top_insight = self._last_result.insights[0]
            summary_parts.append(
                f"最重要的洞察：{top_insight.title}"
            )

        return "\n".join(summary_parts)
